name: Deploy Infrastructure to AWS

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: 'us-east-1'
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v1

      # Deploy the cognito user pool and api gateway endpoint
      - name: terraform-init
        run: terraform -chdir=./terraform init

      - name: terraform-apply
        run: terraform -chdir=./terraform apply -auto-approve -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=fiap.hackathon.authentication.infra.tfstate" -backend-config="region=us-east-1"